elasticsearch:
  image: elasticsearch:latest
  container_name: elasticsearch
  ports:
    - "9200:9200"

kibana:
  image: kibana:latest 
  container_name: kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch
